from django.urls import path
from . import views

urlpatterns = [
    path("", views.HOME, name="home"),
    path('signup/', views.employee_signup, name='signup'),
    path('login/', views.employee_login, name='login'),
    path('logout/', views.employee_logout, name='logout'),
    path("CONTACT", views.CONTACT, name="contact"),
    path("Registrationofemployee", views.REGIEMP, name="REGIEMP"),
    path("adminlogin", views.ADMINLOGIN, name="adminlogin"),
    path("about", views.ABOUT, name="about"),
    path('Tasks', views.assign_task, name='Task'),
    path('task-list/', views.assigned_tasks, name='taskemployeelist'),
    path("REGIEMP", views.REGIEMP, name="regiemp"),
    path("Developers", views.DEV, name="Developers"),
    path("regidment", views.REGIDMENT, name="regidment"),
    path("ADMINLOGIN/AdminDashboard",views.AdminDashboard,name="admindashboard"),
    path('AdminDashboard/assigned-tasks/', views.assigned_tasks, name='assigned_tasks'),
    path('AdminDashboard/task-des/', views.task_des, name='task_des'),
    path('mark_task_finished/<int:task_id>/<email>/', views.mark_task_finished, name='mark_task_finished'),
    path('AdminDashboard/task-end-dates/', views.task_end_dates, name='task_end_dates'),
    path('EMPTaskEndDate', views.EMPTaskEndDate, name='emptaskenddate'),
    path('ADMINLOGIN/AdminDashboard/emplist', views.employee_list, name='employee_list'),   
    path('delete/<int:pk>/', views.delete_employee, name='delete_employee'),
    path('edit/<int:pk>/', views.edit_employee, name='edit_employee'),
    path('departments/', views.department_list, name='department_list'),
    path('search/', views.search_employee, name='search_employee'),
    path('Dlist/', views.department_list, name='dlist'),
    path('search_department/', views.search_department, name='search_department'),
    path('edit_department/<int:department_id>/',views.edit_department, name='edit_department'),
    path('delete_department/<int:department_id>/',views.delete_department, name='delete_department'),
    path('AdminDashboard/TaskReport', views.TaskReport, name='taskreport'),
    path('EMPDashboard', views.EMPDASHBOARD, name='empdashboard'),
    path('EmployeeTask', views.EmployeeTask, name='employeetask'),
    path('TaskDashboard', views.TaskDashboard, name='taskdashboard'),
    path('finished-tasks/', views.finished_tasks_view, name='finished_tasks'),
    path('employee_dashboard/', views.employee_dashboard, name='employee_dashboard'),
    path('update_assignment/<int:task_id>/', views.update_Assignment, name='update_assignment'),
    path('Chamcong', views.timesheet_view, name='chamcong'),
    path('employee_profile/', views.employee_profile, name='employee_profile'),
    path('incomplete-tasks/', views.incomplete_tasks_view, name='incomplete_tasks'),
    path('completed-tasks/', views.completed_tasks_view, name='completed_tasks'),
    path('checkin/', views.check_in_view, name='checkin'),
    path('checkins/', views.checkin_list, name='checkin_list'),
]
